### ISSUE TITLE
Upgrade to rand 0.7.0

### ISSUE THREAD

**Issue by fubuloubu** [RustCrypto/password-hashing#17]
Using this package alongside a project that uses the latest `rand` crate, and getting an incompatibility:
```rust
   Compiling pbkdf2 v0.3.0
error[E0432]: unresolved import `rand::OsRng`
 --> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/pbkdf2-0.3.0/src/simple.rs:7:12
  |
7 | use rand::{OsRng, RngCore};
  |            ^^^^^ no `OsRng` in the root
```

Solution: just upgrade the imports

**Comment by breard-r** [comment]
The `rand` dependency is required only for the `include_simple` feature. If you do not use the simple function then, in your project, you can specify `default-features = false` when including `pbkdf2`.
